<a href="https://colab.research.google.com/github/hussain2505/ML_LAB_2026-27/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas

In [96]:
import pandas as pd

Dataframe

In [97]:
data = {
    "Name": ["Ali", "Rahul", "John","Ravi","Sai","Jack"],
    "Age": [20, 21, 22,23,20,21],
    "Marks": [85, 90, 78,92,89,65]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0    Ali   20     85
1  Rahul   21     90
2   John   22     78
3   Ravi   23     92
4    Sai   20     89
5   Jack   21     65

Display data

In [98]:
df.head()#first five rows

    Name  Age  Marks
0    Ali   20     85
1  Rahul   21     90
2   John   22     78
3   Ravi   23     92
4    Sai   20     89

In [99]:
df.head(3)#given rows of index

    Name  Age  Marks
0    Ali   20     85
1  Rahul   21     90
2   John   22     78

In [100]:
df.tail()#last five rows

    Name  Age  Marks
1  Rahul   21     90
2   John   22     78
3   Ravi   23     92
4    Sai   20     89
5   Jack   21     65

In [101]:
df.tail(2)#given rows of index

   Name  Age  Marks
4   Sai   20     89
5  Jack   21     65

Check dataset information

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

Check rows and columns

In [103]:
df.shape

(6, 3)

In [104]:
df.columns   #give the columns

Index(['Name', 'Age', 'Marks'], dtype='object')

Select a column

In [105]:
df["Age"]

0    20
1    21
2    22
3    23
4    20
5    21
Name: Age, dtype: int64

In [106]:
df[["Name", "Age"]]

    Name  Age
0    Ali   20
1  Rahul   21
2   John   22
3   Ravi   23
4    Sai   20
5   Jack   21

Select rows

In [107]:
df.iloc[0]

Name     Ali
Age       20
Marks     85
Name: 0, dtype: object

In [108]:
df.iloc[0:3]   #continues give the rows

    Name  Age  Marks
0    Ali   20     85
1  Rahul   21     90
2   John   22     78

Filter data

In [109]:
df[df["Marks"] > 80]

    Name  Age  Marks
0    Ali   20     85
1  Rahul   21     90
3   Ravi   23     92
4    Sai   20     89

In [110]:
df[df["Marks"] < 80]

   Name  Age  Marks
2  John   22     78
5  Jack   21     65

Basic statistics

In [111]:
df["Marks"].mean()

np.float64(83.16666666666667)

In [112]:
df["Marks"].max()

92

In [113]:
df["Marks"].min()

65

In [114]:

df["Marks"].sum()

np.int64(499)

Missing values

In [115]:
import pandas as pd


data = {
    "Name": ["Ali", "Rahul", "John", "Sara", "David"],
    "Age": [20, np.nan, 22, 21, np.nan],
    "Marks": [85, 90, np.nan, 78, 88]
}

df = pd.DataFrame(data)

print(df)
print(df.isnull())

    Name   Age  Marks
0    Ali  20.0   85.0
1  Rahul   NaN   90.0
2   John  22.0    NaN
3   Sara  21.0   78.0
4  David   NaN   88.0
    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

Fill missing values

In [116]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

print(df)

    Name   Age  Marks
0    Ali  20.0  85.00
1  Rahul  21.0  90.00
2   John  22.0  85.25
3   Sara  21.0  78.00
4  David  21.0  88.00

Remove missing values

In [117]:
import pandas as pd


data = {
    "Name": ["Ali", "Rahul", "John", "Sara", "David"],
    "Age": [20, np.nan, 22, 21, np.nan],
    "Marks": [85, 90, np.nan, 78, 88]
}

df = pd.DataFrame(data)
df = df.dropna()

print(df)

   Name   Age  Marks
0   Ali  20.0   85.0
3  Sara  21.0   78.0

Unique values

In [118]:
data = {
    "Name": ["Ali", "Rahul", "John","Ravi","Sai","Jack"],
    "Age": [20, 21, 22,23,20,21],
    "Marks": [85, 90, 78,92,89,65]
}

df = pd.DataFrame(data)
df["Name"].unique()

array(['Ali', 'Rahul', 'John', 'Ravi', 'Sai', 'Jack'], dtype=object)

In [119]:
df["Name"].nunique()#count the values

6

Sort data

In [120]:
df.sort_values("Marks")

    Name  Age  Marks
5   Jack   21     65
2   John   22     78
0    Ali   20     85
4    Sai   20     89
1  Rahul   21     90
3   Ravi   23     92

In [121]:
df.sort_values("Marks", ascending=False) # higest marks

    Name  Age  Marks
3   Ravi   23     92
1  Rahul   21     90
4    Sai   20     89
0    Ali   20     85
2   John   22     78
5   Jack   21     65

Add a column

In [122]:
data = {
    "Name": ["Ali", "Rahul", "John","Ravi","Sai","Jack"],
    "Age": [20, 21, 22,23,20,21],
    "Marks": [85, 90, 78,92,89,65]
}

df["Pass"] = df["Marks"] >= 80
print(df)

    Name  Age  Marks   Pass
0    Ali   20     85   True
1  Rahul   21     90   True
2   John   22     78  False
3   Ravi   23     92   True
4    Sai   20     89   True
5   Jack   21     65  False

Delete a column

In [123]:
data = {
    "Name": ["Ali", "Rahul", "John"],
    "Marks": [85, 35, 70]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks
0    Ali     85
1  Rahul     35
2   John     70

Groupby

In [124]:
import pandas as pd

data = {
    "Name": ["Ali", "Rahul", "John", "Ravi", "Sai", "Jack"],
    "Age": [20, 21, 22, 23, 20, 21],
    "Marks": [85, 90, 78, 92, 89, 65]
}

df = pd.DataFrame(data)

result = df.groupby("Age")["Marks"].mean()

print(result)

Age
20    87.0
21    77.5
22    78.0
23    92.0
Name: Marks, dtype: float64

Upload csv file

In [125]:
import pandas as pd

df = pd.read_csv("train.csv")

df.head()

,Student_ID,Name,Maths,Physics,Chemistry,English,Computer_Science,Total,Percentage,Result
0,1,Aarav,85,78,82,88,91,424,84.8,Pass
1,2,Priya,92,89,91,94,96,462,92.4,Pass
2,3,Rahul,76,72,75,79,83,385,77.0,Pass
3,4,Ananya,88,91,86,90,94,449,89.8,Pass
4,5,Arjun,67,65,70,72,75,349,69.8,Pass